//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PopulationRegistering
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PopulationRegisterEntities2 : DbContext
    {
        public PopulationRegisterEntities2()
            : base("name=PopulationRegisterEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accommodation> Accommodation { get; set; }
        public virtual DbSet<Births> Births { get; set; }
        public virtual DbSet<Deaths> Deaths { get; set; }
        public virtual DbSet<Marriages> Marriages { get; set; }
        public virtual DbSet<Person> Person { get; set; }
    }
}
