//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PopulationRegistering
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Marriages = new HashSet<Marriages>();
            this.Marriages1 = new HashSet<Marriages>();
        }
    
        public decimal pesel { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public bool sex { get; set; }
        public int permanentAddress_ID { get; set; }
        public int temporaryAddress_ID { get; set; }
        public Nullable<bool> isDead { get; set; }
    
        public virtual Accommodation Accommodation { get; set; }
        public virtual Accommodation Accommodation1 { get; set; }
        public virtual Births Births { get; set; }
        public virtual Deaths Deaths { get; set; }
        public virtual ICollection<Marriages> Marriages { get; set; }
        public virtual ICollection<Marriages> Marriages1 { get; set; }
    }
}
